### ISSUE TITLE
検索時のオートコンプリート機能

### ISSUE THREAD

**Issue by aiueo49** [aiueo49/tanka_tukutta-#99]
# As Is

検索フォームで検索をかける時、全文入力しなければならない手間がある。
# To Be 

入力途中に文章の続きが保管される。
または、候補が表示される。
# アクション

https://github.com/afcapel/stimulus-autocomplete を使用する。
- [x] importmapでstimulus-autocompleteをインストール
- [x] app/javascript/controllers/application.jsにstimulus-autocompleteの設定を追加
- [x] 自動補完部分のビューを作る
- [x] 検索フォームとオートコンプリート部分のビューを紐付ける
- [x] searchアクションとルーティングを設定する

参考
https://qiita.com/Yamamoto-Masaya1122/items/879d6eb540ce4e05cfe5
https://github.com/afcapel/stimulus-autocomplete

**Comment by aiueo49** [comment]
❯ ./bin/importmap pin stimulus-autocomplete
Pinning "stimulus-autocomplete" to vendor/javascript/stimulus-autocomplete.js via download from https://ga.jspm.io/npm:stimulus-autocomplete@3.1.0/src/autocomplete.js
Pinning "@hotwired/stimulus" to vendor/javascript/@hotwired/stimulus.js via download from https://ga.jspm.io/npm:@hotwired/stimulus@3.2.2/dist/stimulus.js

tanka_tukitta- on  99_autocomplete [!?] via 🐳 desktop-linux via 💎 v3.3.0 on ☁️  (ap-northeast-1) took 2s
❯

**Comment by aiueo49** [comment]
`config/importmap.rb`
```
# Pin npm packages by running ./bin/importmap

pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "@hotwired--stimulus.js" # @3.2.2
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin_all_from "app/javascript/controllers", under: "controllers"
pin "stimulus-autocomplete" # @3.1.0

```

**Comment by aiueo49** [comment]
`app/javascript/controllers/application.js`
```
import { Application } from "@hotwired/stimulus"
import { Autocomplete } from 'stimulus-autocomplete'  #コンポーネントを読み込むための記述

const application = Application.start()
application.register('autocomplete', Autocomplete)  #コンポーネントにあるAutocompleteコントローラを使えるようにするための記述

// Configure Stimulus development experience
application.debug = false
window.Stimulus   = application

export { application }
```

**Comment by aiueo49** [comment]
ブラウザ検証ツール内でエラー発生
```
@hotwired--stimulus-…5d1e260aaa403e.js:1 Error connecting controller

Error: Missing target element "results" for "autocomplete" controller
    at extended.get (@hotwired--stimulus-…0aaa403e.js:1:44896)
    at get resultsShown (stimulus-autocomplet…247146555.js:1:5428)
    at extended.close (stimulus-autocomplet…247146555.js:1:5107)
    at extended.connect (stimulus-autocomplet…3247146555.js:1:416)
    at Context.connect (@hotwired--stimulus-…0aaa403e.js:1:28658)
    at Module.connectContextForScope (@hotwired--stimulus-…0aaa403e.js:1:31879)
    at Router.scopeConnected (@hotwired--stimulus-…0aaa403e.js:1:39465)
    at ScopeObserver.elementMatchedValue (@hotwired--stimulus-…0aaa403e.js:1:37597)
    at ValueListObserver.tokenMatched (@hotwired--stimulus-…0aaa403e.js:1:18103)
    at TokenListObserver.tokenMatched (@hotwired--stimulus-…0aaa403e.js:1:16670)

Object
controller
: 
extended {context: Context, onKeydown: ƒ, onEscapeKeydown: ƒ, onArrowDownKeydown: ƒ, onArrowUpKeydown: ƒ, …}
element
: 
div
identifier
: 
"autocomplete"
[[Prototype]]
: 
Object
```

**Comment by aiueo49** [comment]
resultsターゲットを追加
```
<div data-controller="autocomplete">
  <input data-autocomplete-target="input" type="text" autocomplete="off">
  <input data-autocomplete-target="hidden" type="hidden">
  <div data-autocomplete-target="results"></div>
</div>
```

タイポ修正

ルーティング修正
```
Rails.application.routes.draw do
  # ...
  get '/search', to: 'posts#search'
  # ...
end
```

**Comment by aiueo49** [comment]
正常動作を確認。
・resultsターゲットが必要だったこと
・jsのコントローラが足りなかったこと
・ルーティングが正しくなかったこと
以上が原因だった。

**Comment by aiueo49** [comment]
現在は、ポストのタイトルカラムだけがオートコンプリートの対象。
これを、コンテントカラムも対象にするように修正する。

**Comment by aiueo49** [comment]
レイアウトが崩れるので直す

**Comment by aiueo49** [comment]
レイアウトは、フォームのかどまるをやめた。
